CREATE DATABASE qlcc
CREATE TABLE DUAN(
	MADA VARCHAR(4) PRIMARY KEY,
	TENDA NVARCHAR(50),
	NAMBATDAU INT
)
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(4) PRIMARY KEY,
	HOTEN NVARCHAR(20),
	NGAYSINH DATE,
	LUONG MONEY,
	PHAI NVARCHAR(4)
)

CREATE TABLE CHAMCONG
(
	MANV VARCHAR(4),
	MADA VARCHAR(4),
	PRIMARY KEY (MANV,MADA),
	SOGIO INT,
	FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),
	FOREIGN KEY (MADA) REFERENCES dbo.DUAN(MADA)
)

INSERT INTO dbo.DUAN
(
    MADA,
    TENDA,
    NAMBATDAU
)
VALUES
('D1',N'Phần mềm dạy online' ,2021),
('D2',N'Mạng Agent' ,2022),
('D3',N'Quản lí sách' ,2020)

INSERT INTO dbo.NHANVIEN
(
    MANV,
    HOTEN,
    NGAYSINH,
    LUONG,
    PHAI
)
VALUES
('N01',N'Lê Văn Tèo','2002-03-01',19000000,N'Nam'),
('N02',N'Ngọc Giàu','1998-03-03',6000000,N'Nam'),
('N03',N'Đặng Thị Hiếu','1996-05-01',60000000,N'Nữ');

INSERT INTO dbo.CHAMCONG
(
    MANV,
    MADA,
    SOGIO
)
VALUES
('N01','D1',220),
('N03','D1',200),
('N01','D3',90)
--c2
SELECT MANV,HOTEN,NGAYSINH FROM dbo.NHANVIEN
WHERE LUONG > 7000000 AND PHAI =N'nữ'
--c3
SELECT t01.MADA,TENDA FROM dbo.DUAN t01 
JOIN dbo.CHAMCONG t02 ON t01.MADA=t02.MADA
JOIN dbo.NHANVIEN t03 ON t03.MANV=t02.MANV
where HOTEN=N'Ngọc Giàu'
group by t01.MADA,TENDA
--c4
SELECT t01.MANV,HOTEN, sum(SOGIO)FROM dbo.NHANVIEN t01 
join dbo.CHAMCONG t02 on t01.MANV=t02.MANV
group by t01.MANV,HOTEN
having SUM(sogio)>300
--c5
select t01.MANV,HOTEN,COUNT(t02.MaDA) from NHANVIEN t01
join dbo.CHAMCONG t02 on t01.MANV=t02.MANV
join dbo.DUAN t03 on t03.MADA=t02.MADA
group by  t01.MANV,HOTEN
--c6
INSERT INTO dbo.NHANVIEN
(
    MANV,
    HOTEN,
    NGAYSINH,
    LUONG,
    PHAI
)
values ('D04', N'Nguyễn Xuân Chung','2020-06-05',11000000,N'nam' )
select * from NHANVIEN
--c7
update DUAN
set NAMBATDAU ='2019' where TENDA=N'Mạng Agent'
select * from DUAN
--c8
delete from dbo.DUAN where mada=(  select dbo.DUAN.MADA from dbo.DUAN EXCEPT SELECT dbo.CHAMCONG.MADA from dbo.CHAMCONG )
SELECT * FROM dbo.DUAN

